In [1]:
#arraycreation andproperties
import numpy as np
a=np.arange(17)
b=np.arange(25)

In [2]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [3]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
c=np.arange(15).reshape(3,5)

In [6]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
print(c.ndim)

2


In [8]:
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(type(c))


(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [9]:
b=np.array([1.0,2.0,3.0,4.0,5])
print(b)

[1. 2. 3. 4. 5.]


In [10]:
print(b.dtype)
print(type(b))

float64
<class 'numpy.ndarray'>


In [12]:
c=np.eye(10)
dtype=np.float64

In [13]:
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
d = np.linspace(-1,3,21, endpoint=True)
print(d)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6
  1.8  2.   2.2  2.4  2.6  2.8  3. ]


In [32]:
e = np.logspace(-1, 3, 21 ,endpoint=True, base=10)
print(e)

[1.00000000e-01 1.58489319e-01 2.51188643e-01 3.98107171e-01
 6.30957344e-01 1.00000000e+00 1.58489319e+00 2.51188643e+00
 3.98107171e+00 6.30957344e+00 1.00000000e+01 1.58489319e+01
 2.51188643e+01 3.98107171e+01 6.30957344e+01 1.00000000e+02
 1.58489319e+02 2.51188643e+02 3.98107171e+02 6.30957344e+02
 1.00000000e+03]


In [33]:
f = np.fromfunction(lambda i, j: i == j, (4, 4), dtype=int)
f

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [34]:
#array operations


In [35]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
a*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [41]:
a+a


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
a*a


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [44]:
c=a.transpose()
c

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
a@c

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [47]:
print(a)
a.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [48]:
a.sum()

66

In [49]:
print(a.min(),a.max())

0 11


In [50]:
#universal functions

In [51]:
c=a*np.pi/12.0
print(c)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]


In [56]:
d=np.cos(c)
print(d)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  2.58819045e-01  6.12323400e-17 -2.58819045e-01]
 [-5.00000000e-01 -7.07106781e-01 -8.66025404e-01 -9.65925826e-01]]


In [57]:
e=c+d
print(e)

[[1.         1.22772521 1.38962418 1.49250494]
 [1.54719755 1.56781598 1.57079633 1.57377667]
 [1.5943951  1.64908771 1.75196847 1.91386744]]


In [58]:
#array slicing,accessing subarrays

In [59]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a[3]

3

In [63]:
print(a[2:3])

[2]


In [64]:
a[2:4]

array([2, 3])

In [65]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#multidimensionalarrays

In [67]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
a[1,1]


6

In [69]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [70]:
a[:,1]

array([ 1,  6, 11])

In [71]:
a=a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [72]:
for r in a:
    print(r)
a=np.arange(15).reshape(3,5)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [75]:
#copyingarrays
b=np.arange(10)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
c=b
c is b

True

In [78]:
c.shape=(2,5)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [79]:
b.shape
c is b

True

In [80]:
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [81]:
b=np.arange(12)
d=b[:]
b.shape=[3,4]
print(b)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [82]:
d[1]=-1

In [83]:
print(b)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [85]:
print(d)



[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [86]:
#boolean indexing

In [87]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a[a>3]=0
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
a[a==0]=-1
a


array([[-1,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [91]:
a==-1

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [92]:
a>3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
#avoiding loops


In [99]:
m = 36
n= 72
xmin = ymin = 2.0
xmax = ymax = 4.0

x = np.linspace(xmin, xmax, m, endpoint=False)
y = np.linspace(ymin, ymax, n, endpoint=False)

print(x.shape)
print(y.shape)
y

(36,)
(72,)


array([2.        , 2.02777778, 2.05555556, 2.08333333, 2.11111111,
       2.13888889, 2.16666667, 2.19444444, 2.22222222, 2.25      ,
       2.27777778, 2.30555556, 2.33333333, 2.36111111, 2.38888889,
       2.41666667, 2.44444444, 2.47222222, 2.5       , 2.52777778,
       2.55555556, 2.58333333, 2.61111111, 2.63888889, 2.66666667,
       2.69444444, 2.72222222, 2.75      , 2.77777778, 2.80555556,
       2.83333333, 2.86111111, 2.88888889, 2.91666667, 2.94444444,
       2.97222222, 3.        , 3.02777778, 3.05555556, 3.08333333,
       3.11111111, 3.13888889, 3.16666667, 3.19444444, 3.22222222,
       3.25      , 3.27777778, 3.30555556, 3.33333333, 3.36111111,
       3.38888889, 3.41666667, 3.44444444, 3.47222222, 3.5       ,
       3.52777778, 3.55555556, 3.58333333, 3.61111111, 3.63888889,
       3.66666667, 3.69444444, 3.72222222, 3.75      , 3.77777778,
       3.80555556, 3.83333333, 3.86111111, 3.88888889, 3.91666667,
       3.94444444, 3.97222222])

In [100]:
#timeoutcode

In [103]:
import time
import numpy as np
m=32
n=64
x=np.linspace(2.0,4.0,m,endpoint=False)
y=np.linspace(2.0,4.0,n,endpoint=False)


In [104]:
t0 = time.time()

g = np.zeros((m, n))

for i in range(m):
    for j in range(n):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [105]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[2.     2.0625 2.125  2.1875 2.25   2.3125 2.375  2.4375 2.5    2.5625
 2.625  2.6875 2.75   2.8125 2.875  2.9375 3.     3.0625 3.125  3.1875
 3.25   3.3125 3.375  3.4375 3.5    3.5625 3.625  3.6875 3.75   3.8125
 3.875  3.9375]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2.]
[2.      2.03125 2.0625  2.09375 2.125   2.15625 2.1875  2.21875 2.25
 2.28125 2.3125  2.34375 2.375   2.40625 2.4375  2.46875 2.5     2.53125
 2.5625  2.59375 2.625   2.65625 2.6875  2.71875 2.75    2.78125 2.8125
 2.84375 2.875   2.90625 2.9375  2.96875 3.      3.03125 3.0625  3.09375
 3.125   3.15625 3.1875  3.21875 3.25    3.28125 3.3125  3.34375 3.375
 3.40625 3.4375  3.46875 3.5     3.53125 3.5625  3.59375 3.625   3.65625
 3.6875  3.71875 3.75    3.78125 3.8125  3.8

In [106]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [107]:
#array concatenation and splitting

In [108]:
x=np.array([1,2,3,4,5])
y=np.array([5,4,3,2,1])
np.concatenate([y,x])


array([5, 4, 3, 2, 1, 1, 2, 3, 4, 5])

In [109]:
z=[6,4,5]
print(np.concatenate([x,y,z]))

[1 2 3 4 5 5 4 3 2 1 6 4 5]


In [110]:
grid=np.array([[10,20,40],[40,50,60]])

In [112]:
np.concatenate([[grid],[grid]])

array([[[10, 20, 40],
        [40, 50, 60]],

       [[10, 20, 40],
        [40, 50, 60]]])

In [113]:
np.concatenate([grid, grid], axis=1)

array([[10, 20, 40, 10, 20, 40],
       [40, 50, 60, 40, 50, 60]])

In [114]:
#splitting of arrays


In [124]:
x=[1,2,3,4,5,6,7,8,8]
x1,x2,x3,x4=np.split(x,[3,5,6])

In [125]:
print(x1,x2,x3,x4)

[1 2 3] [4 5] [6] [7 8 8]


In [127]:
grid = np.arange(30).reshape((6, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [128]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]
 [25 26]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]]


In [129]:
#aggregates


In [130]:
x=np.arange(1,12)
print(x)
np.add.reduce(x)

[ 1  2  3  4  5  6  7  8  9 10 11]


66

In [131]:
np.multiply.reduce(x)

39916800

In [132]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [133]:
np.multiply.accumulate(x)

array([       1,        2,        6,       24,      120,      720,
           5040,    40320,   362880,  3628800, 39916800], dtype=int32)